title: Pablo Herrero Ortiz | Digital Portfolio
author: Pablo Herrero Ortiz
email: pablo.herrort@gmail.com
timezone: Europe/Amsterdam
description: "Digital Portfolio of Pablo Herrero Ortiz"

author:
  github: pabloherreroo 
  linkedin: pabloherreroortiz

remote_theme: "yousinix/portfolYOU"

url: "https://pabloherrero.github.io" 
baseurl: "" 

markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme
