title: Pablo Herrero Ortiz | Digital Portfolio
author: Pablo Herrero Ortiz

remote_theme: pages-themes/minimal@v0.2.0

baseurl: "" 
url: "https://pabloherrero.github.io" 

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
